{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nodejs-demo-app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}  # Reference ingress.host from values.yaml
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nodejs-demo-app.fullname" . }}
                port:
                  number: 80
{{- end }}
